id = "hivacruz-theme"
name = "Hivacruz Theme"
version = "0.1.0"
schema_version = 1
authors = ["Yann Defretin <yann@defret.in>"]
description = "A dark blue theme."
repository = "https://github.com/kinoute/zed-hivacruz-theme"
